Copy & paste with middle mouse button click
NordicSemiconductor/pc-nrfconnect-serial-terminal pull request #98
Opened 2024-11-27 10:30 UTC by KievDevel

2024-11-27 11:07 UTC, kylebonnici commented on src/components/Terminal/Terminal.tsx
> +                xtermRef.current?.terminal.clearSelection();
Consider returning here and removing hasSelection below from if

2024-11-28 07:48 UTC, greg-fer requested changes
Don't merge this. I need to update the docs in this PR. (You can also do it if you're pressed for time, but I should be done by EoD.)

2024-11-28 07:48 UTC, greg-fer commented on Changelog.md
> +-   Ability to copy and paste with the middle mouse button click.
```suggestion
-   Ability to copy and paste with the middle mouse button.
```

2024-12-01 20:05 UTC, KievDevel commented on Changelog.md
> +-   Support for copying and pasting the console output with the middle mouse
```suggestion
-   Support for copying and pasting the terminal output with the middle mouse
```

2024-12-01 20:06 UTC, KievDevel commented on doc/docs/overview.md
> +      You can select the console output and use the middle mouse button to copy and paste it.
```suggestion
      You can select the terminal output and use the middle mouse button to copy and paste it.
```

2024-12-01 20:06 UTC, KievDevel commented on src/components/Terminal/Terminal.tsx
> +                            // onMouseDown={e => {
Will remove before merge

2024-12-02 08:59 UTC, greg-fer approved these changes

2025-05-14 01:19 UTC, merged